POST http://localhost:6000/products
Content-Type: application/json

{
    "nameProduct":"Nasi campur",
    "categories":"minuman",
    "madeIn":"smg"
}
###
DELETE http://localhost:6000/products/675337b95dd8e2b908e666
###

PATCH http://localhost:6000/products/675336b45dd8e2b908e666a2
Content-Type: application/json

{
    "madeIn":"Ngawi"
}

###
GET http://localhost:6000/products
###